"""Public API for the core OrchestrateBench package surface."""

from .automation import SUPPORTED_POLICY_FACTORIES, build_named_policies
from .core import (
    AgentTask,
    DependencyGraph,
    ExecutionTrace,
    FixedPolicy,
    HeuristicPolicy,
    OrchestratorAction,
    OrchestratorBench,
    RetryPolicy,
    RetryRecord,
    RoutingDecision,
    SubAgentType,
    TaskStatus,
)
from .data import (
    SAMPLE_TASKS_RAW,
    make_benchmark_tasks,
    make_devops_deploy_workflow,
    make_execution_trace,
    make_finance_approval_workflow,
    make_hr_onboarding_workflow,
    make_linear_pipeline,
    make_task,
)
from .evaluate import (
    confidence_calibration,
    mean_cost,
    mean_latency,
    mean_retry_rate,
    orchestration_efficiency_score,
    per_class_routing_metrics,
    policy_comparison,
    routing_accuracy,
    routing_confusion_matrix,
    routing_distribution,
    routing_macro_f1,
    skip_rate,
    success_rate,
    task_dependency_score,
    throughput_score,
)
from .failures import FailureInjector, FailureMode, measure_cascade, recovery_rate_by_mode
from .measured_runs import (
    MeasuredExp2Record,
    MeasuredExp3Record,
    load_exp2_measured_records,
    load_exp3_measured_records,
)
from .measured_templates import (
    DEFAULT_MEASURED_POLICIES,
    build_exp2_measured_skeleton,
    build_exp3_measured_skeleton,
)
from .routing_comparison import (
    LLMPolicy,
    format_comparison_report,
    make_routing_eval_set,
    run_routing_comparison,
)
from .statistics import bootstrap_ci, metric_ci, paired_bootstrap_test, paired_bootstrap_values

__all__ = [
    "AgentTask",
    "DependencyGraph",
    "ExecutionTrace",
    "FailureInjector",
    "FailureMode",
    "FixedPolicy",
    "HeuristicPolicy",
    "LLMPolicy",
    "MeasuredExp2Record",
    "MeasuredExp3Record",
    "OrchestratorAction",
    "OrchestratorBench",
    "RetryPolicy",
    "RetryRecord",
    "RoutingDecision",
    "SAMPLE_TASKS_RAW",
    "SUPPORTED_POLICY_FACTORIES",
    "SubAgentType",
    "TaskStatus",
    "DEFAULT_MEASURED_POLICIES",
    "bootstrap_ci",
    "build_exp2_measured_skeleton",
    "build_exp3_measured_skeleton",
    "build_named_policies",
    "confidence_calibration",
    "format_comparison_report",
    "load_exp2_measured_records",
    "load_exp3_measured_records",
    "make_benchmark_tasks",
    "make_devops_deploy_workflow",
    "make_execution_trace",
    "make_finance_approval_workflow",
    "make_hr_onboarding_workflow",
    "make_linear_pipeline",
    "make_routing_eval_set",
    "make_task",
    "mean_cost",
    "mean_latency",
    "mean_retry_rate",
    "measure_cascade",
    "metric_ci",
    "orchestration_efficiency_score",
    "paired_bootstrap_test",
    "paired_bootstrap_values",
    "per_class_routing_metrics",
    "policy_comparison",
    "recovery_rate_by_mode",
    "routing_accuracy",
    "routing_confusion_matrix",
    "routing_distribution",
    "routing_macro_f1",
    "run_routing_comparison",
    "skip_rate",
    "success_rate",
    "task_dependency_score",
    "throughput_score",
]
