"""End-to-end automation helpers for Exp 2/3 measured-style runs."""

from __future__ import annotations

from pathlib import Path
from typing import Callable, Dict, List, Sequence

from .core import FixedPolicy, HeuristicPolicy, RetryPolicy
from .experiments import (
    collect_cascade_records,
    collect_failure_recovery_records,
    write_records_csv,
)
from .failures import FailureMode
from .measured_templates import DEFAULT_MEASURED_POLICIES

PolicyFactory = Callable[[], object]


SUPPORTED_POLICY_FACTORIES: Dict[str, PolicyFactory] = {
    "fixed": lambda: FixedPolicy(),
    "heuristic": lambda: HeuristicPolicy(),
    "retry(heuristic)": lambda: RetryPolicy(HeuristicPolicy(), failure_rate=0.0, seed=0),
}


def build_named_policies(
    policy_names: Sequence[str] = DEFAULT_MEASURED_POLICIES,
) -> Dict[str, object]:
    """Instantiate the supported automation policy suite by name."""
    policies: Dict[str, object] = {}
    for policy_name in policy_names:
        factory = SUPPORTED_POLICY_FACTORIES.get(policy_name)
        if factory is None:
            supported = ", ".join(sorted(SUPPORTED_POLICY_FACTORIES))
            raise ValueError(
                f"Unsupported policy '{policy_name}'. Supported policies: {supported}"
            )
        policies[str(policy_name)] = factory()
    return policies


def build_auto_exp2_measured_records(
    *,
    policy_names: Sequence[str] = DEFAULT_MEASURED_POLICIES,
    modes: Sequence[FailureMode] = tuple(FailureMode),
    n_runs: int = 20,
    seed: int = 0,
) -> List[Dict[str, object]]:
    """Collect Exp 2 harness records and normalize them to measured-file shape."""
    policy_map = build_named_policies(policy_names)
    records = collect_failure_recovery_records(
        policy_map,
        modes=list(modes),
        n_runs=n_runs,
        seed=seed,
    )
    normalized: List[Dict[str, object]] = []
    for record in records:
        scenario_id = (
            f"{record['workflow']}__{record['failure_mode']}__"
            f"inj{int(record['injection_stage'])}__run{int(record['run']):04d}"
        )
        normalized.append(
            {
                "policy": str(record["policy"]),
                "workflow": str(record["workflow"]),
                "failure_mode": str(record["failure_mode"]),
                "run": int(record["run"]),
                "seed": int(record["seed"]),
                "injection_stage": int(record["injection_stage"]),
                "scenario_id": scenario_id,
                "injected_task_success": bool(record["injected_task_success"]),
                "final_task_success": bool(record["final_task_success"]),
                "cascade_radius": float(record["cascade_radius"]),
                "recovery_completeness": float(record["recovery_completeness"]),
                "time_to_detection_ms": float(record["time_to_detection_ms"]),
                "escalated": bool(record["escalated"]),
                "escalation_latency_ms": float(record["escalation_latency_ms"]),
                "annotator": "auto_harness",
                "notes": "Generated by run_exp23_pipeline.py",
            }
        )
    return normalized


def build_auto_exp3_measured_records(
    *,
    policy_names: Sequence[str] = DEFAULT_MEASURED_POLICIES,
    depths: Sequence[int] = (3, 5, 7),
    injection_stages: Sequence[int] = (0, 1, 2),
    mode: FailureMode = FailureMode.CONTEXT_POLLUTION,
    n_runs: int = 20,
    seed: int = 0,
) -> List[Dict[str, object]]:
    """Collect Exp 3 harness records and normalize them to measured-file shape."""
    policy_map = build_named_policies(policy_names)
    records = collect_cascade_records(
        policy_map,
        depths=list(depths),
        injection_stages=list(injection_stages),
        mode=mode,
        n_runs=n_runs,
        seed=seed,
    )
    normalized: List[Dict[str, object]] = []
    for record in records:
        scenario_id = (
            f"depth{int(record['depth'])}__{record['failure_mode']}__"
            f"inj{int(record['injection_stage'])}__run{int(record['run']):04d}"
        )
        normalized.append(
            {
                "policy": str(record["policy"]),
                "depth": int(record["depth"]),
                "failure_mode": str(record["failure_mode"]),
                "run": int(record["run"]),
                "seed": int(record["seed"]),
                "injection_stage": int(record["injection_stage"]),
                "scenario_id": scenario_id,
                "injected_task_success": bool(record["injected_task_success"]),
                "final_task_success": bool(record["final_task_success"]),
                "cascade_radius": float(record["cascade_radius"]),
                "recovery_completeness": float(record["recovery_completeness"]),
                "time_to_detection_ms": float(record["time_to_detection_ms"]),
                "escalated": bool(record["escalated"]),
                "escalation_latency_ms": float(record["escalation_latency_ms"]),
                "annotator": "auto_harness",
                "notes": "Generated by run_exp23_pipeline.py",
            }
        )
    return normalized


def write_auto_measured_records(
    records: List[Dict[str, object]],
    path: str | Path,
) -> None:
    """Write auto-collected measured records in CSV form."""
    write_records_csv(records, path)
